apiVersion: v1
kind: Service
metadata:
  name: pgsqlsvc
  labels:
    app: pgsql-database
spec:
  ports:
  - port: 5432
    name: db
  clusterIP: None
  selector:
    app: pgsql
---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "cl-vol" 
spec:
  capacity:
    storage: "5Gi" 
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  gcePersistentDisk: 
    fsType: "ext4" 
    pdName: "cl-gcedisk-pv1"
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: pgsql
spec:
  serviceName: "pgsql"
  replicas: 1
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:9.6
        env:
        - name: PGDATA
          value: "/var/lib/postgresql/data/db-files/"
        ports:
        - containerPort: 5432
          name: db
        volumeMounts:
        - name: cl-vol 
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: cl-vol 
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: manual 
      resources:
        requests:
          storage: 5Gi
