apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: phppgadmin
spec:
  selector:
    matchLabels:
      app: k8s
      tier: phppgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s
        tier: phppgadmin
    spec:
      containers:
      - name: phppgadmin
        image: zhajor/docker-phppgadmin
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: DB_HOST
            value: pgsqlsvc
          - name: DB_PORT
            value: "5432"
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phppgadmin
  labels:
    app: k8s
    tier: phppgadmin
spec:
  type: LoadBalancer 
  ports:
  - port: 80
  selector:
    app: k8s
    tier: phppgadmin
