apiVersion: apps/v1 # for versions after 1.9.0 use apps/v1beta1
kind: Deployment
metadata:
  name: phppgadmin
spec:
  selector:
    matchLabels:
      app: phppgadmin 
  replicas: 1
  template:
    metadata:
      labels:
        app: phppgadmin 
    spec:
      containers:
      - name: phppgadmin
        image: zhajor/docker-phppgadmin
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: DB_HOST
            value: pgsql-0.pgsql
          - name: DB_PORT
            value: "5432"
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phppgadmin
  labels:
    app: phppgadmin
spec:
  type: LoadBalancer 
  ports:
  - port: 80
  selector:
    app: phppgadmin
